# Generated by Django 5.0.6 on 2024-06-24 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_contact_birth_date_customuser_birth_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
