# Generated by Django 5.0.6 on 2024-06-24 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('file', models.FileField(upload_to='uploads/', verbose_name='Файл')),
                ('category', models.CharField(choices=[('image', 'Зображення'), ('document', 'Документи'), ('video', 'Відео'), ('other', 'Інше')], default='other', max_length=10, verbose_name='Категорія')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завантаження')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
