# Generated by Django 5.0.6 on 2024-06-24 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('working_with_files', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
