# Generated by Django 5.0.6 on 2024-06-24 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
